export const MOCK_PROJECTS = [
  {
    id: 1,
    title: "DeFi Dashboard Frontend",
    description:
      "Looking for an experienced React/Solana developer to build a responsive dashboard for our DeFi protocol. Must have experience with web3.js/anchor.",
    budget: "1,500 USDC",
    posted: "2 hours ago",
    deadline: "2 Weeks",
    skills: ["React", "TypeScript", "Solana", "Tailwind", "Web3.js"],
    category: "Frontend",
    proposals: 5,
    client: {
      name: "Alpha Protocol",
      rating: 4.8,
      jobsPosted: 12,
      totalSpent: "45k USDC",
    },
    status: "Active",
    progress: 40,
    milestones: [
      {
        id: 101,
        title: "UI Components",
        amount: "500 USDC",
        status: "Completed",
        dueDate: "Jan 20",
      },
      {
        id: 102,
        title: "Wallet Integration",
        amount: "500 USDC",
        status: "In Progress",
        dueDate: "Feb 01",
      },
      {
        id: 103,
        title: "Final Polish",
        amount: "500 USDC",
        status: "Pending",
        dueDate: "Feb 10",
      },
    ],
  },
  {
    id: 2,
    title: "Rust Smart Contract Audit",
    description:
      "Need a security expert to review our Anchor programs before mainnet launch. Focus on re-entrancy, access control, and PDA derivation validation.",
    budget: "3,000 USDC",
    posted: "5 hours ago",
    deadline: "1 Week",
    skills: ["Rust", "Anchor", "Security", "Auditing"],
    category: "Smart Contract",
    proposals: 2,
    client: {
      name: "SafeDeFi",
      rating: 5.0,
      jobsPosted: 3,
      totalSpent: "12k USDC",
    },
    status: "Pending Approval",
    progress: 100,
    milestones: [
      {
        id: 201,
        title: "Initial Review",
        amount: "1,500 USDC",
        status: "Completed",
        dueDate: "Jan 15",
      },
      {
        id: 202,
        title: "Final Report",
        amount: "1,500 USDC",
        status: "Pending Approval",
        dueDate: "Jan 22",
      },
    ],
  },
  {
    id: 3,
    title: "NFT Gen Art Script",
    description:
      "Python script needed to generate metadata and images for a 10k collection. Layers provided.",
    budget: "500 USDC",
    posted: "1 day ago",
    deadline: "3 Days",
    skills: ["Python", "NFT", "Metaplex", "Image Processing"],
    category: "Scripting",
    proposals: 12,
    client: {
      name: "MoonCreators",
      rating: 4.5,
      jobsPosted: 8,
      totalSpent: "5k USDC",
    },
    status: "Completed",
    progress: 100,
    milestones: [
      {
        id: 301,
        title: "Script Delivery",
        amount: "500 USDC",
        status: "Paid",
        dueDate: "Jan 10",
      },
    ],
  },
  {
    id: 4,
    title: "Mobile Wallet App Integration",
    description:
      "Integrate Solana Pay request links into an existing React Native mobile wallet.",
    budget: "2,000 USDC",
    posted: "2 days ago",
    deadline: "3 Weeks",
    skills: ["React Native", "Mobile", "Solana Pay", "Android", "iOS"],
    category: "Mobile",
    proposals: 8,
    client: {
      name: "WalletX",
      rating: 4.9,
      jobsPosted: 25,
      totalSpent: "120k USDC",
    },
    status: "Disputed",
    progress: 80,
    milestones: [
      {
        id: 401,
        title: "Integration",
        amount: "2,000 USDC",
        status: "Disputed",
        dueDate: "Jan 18",
      },
    ],
  },
];
